functionality:
  name: "combine_columns"
  namespace: "demo"
  version: "main_build"
  authors: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--id"
    alternatives: []
    example: []
    default:
    - "combine_columns"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "eddelbuettel/r2u:22.04"
  target_organization: "viash-io/viash_project_template"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/viash-io/viash_project_template"
  setup: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/viash_project_template/viash_project_template/src/demo/combine_columns/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/viash_project_template/viash_project_template/target/docker/demo/combine_columns"
  executable: "/home/runner/work/viash_project_template/viash_project_template/target/docker/demo/combine_columns/combine_columns"
  viash_version: "0.7.1"
  git_commit: "1f550b941557875c484f8594e7e1550661106f01"
  git_remote: "https://github.com/viash-io/viash_project_template"
