functionality:
  name: "remove_comments"
  namespace: "demo"
  version: "main_build"
  authors: []
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    example:
    - "file.tsv"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    example:
    - "file.tsv"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--id"
    alternatives: []
    example: []
    default:
    - "remove_comments"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:20.04"
  target_organization: "viash-io/viash_project_template"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/viash-io/viash_project_template"
  setup: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/viash_project_template/viash_project_template/src/demo/remove_comments/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/viash_project_template/viash_project_template/target/nextflow/demo/remove_comments"
  executable: "/home/runner/work/viash_project_template/viash_project_template/target/nextflow/demo/remove_comments/remove_comments"
  viash_version: "0.6.7"
  git_commit: "847d5a1884d340cd17d1b3d6509ed78920c91333"
  git_remote: "https://github.com/viash-io/viash_project_template"
